1. テンソル

### 1. テンソル

Tensor(テンソル)：PyTorchの基本データ型<br>
PyTorchではテンソル型の変数を使用してモデルの入力，出力，パラメータを表現<br>
ndarrayに似ているが，違いとしてはGPU上で使用できる．

In [3]:
import torch
import numpy as np

In [6]:
# データをテンソル変換
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
# ndarrayをテンソル変換
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
# 他のテンソルから新しいテンソルを作成．基本引数のテンソルの形やデータ型を引き継ぐ
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0585, 0.3386],
        [0.9954, 0.9315]]) 



In [11]:
rand_tensor = torch.rand((2,3))
ones_tensor = torch.ones(2,3)
zeros_tensor = torch.zeros(2,3)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3736, 0.9291, 0.4121],
        [0.2624, 0.5562, 0.8196]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# テンソルの属性
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
# デバイスの確認
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu
